### ISSUE TITLE
no audio playing using  vban_receptor (raspian, alsa)

### ISSUE THREAD

**Issue by Pomax** [quiniouben/vban#34] opened 2019-04-06 03:47 UTC
I followed the instructions to install this by installing the libs and headers necessary, running the autogen script, ./configure with `--disable-pulseaudio --disable-jack` arguments, `make` and `make install`, and I have a working `vban_receptor` command available now.

However, when I run the receptor command, things go wrong:

```bash
pi@raspberrypi:~/Documents/git/vban $ vban_receptor -i 192.168.1.24 -p 6980 -s DAW
vban_receptor veersion 2.1.0

Error: alsa_write: short write (expected 256, wrote 72)
Error: alsa_write: snd_pcm_writei failed: Broken pipe
ALSA lib pcm.c:8306(snd_pcm_recover) underrun occurred
Error: alsa_write: snd_pcm_writei failed: Broken pipe
ALSA lib pcm.c:8306(snd_pcm_recover) underrun occurred
Error: alsa_write: snd_pcm_writei failed: Broken pipe
ALSA lib pcm.c:8306(snd_pcm_recover) underrun occurred
[...]
```
(the longer I leave it running, the more this error repeats, with different values for `wrote`).

I verified that the IP, port, and stream name involved are correct, and if I try to just play a random youtube video in Chromium, I do hear audio, so something seems to be pretty wrong?

**Comment by Pomax** [comment] 2019-04-09 22:00
@quiniouben any idea? =/

**Comment by quiniouben** [comment] 2019-04-10 06:12
Hi @Pomax , sorry for the delay, times are busy this year...
I am not sure to understand if you have or haven't correct audio going through. Have you ?

About this error, if it repeats very quickly, then probably something is wrong with the alsa interface used.
If it occurs from time to time (let's say once or twice per half minute), well, I have seen this in the past and this is the drawback of the simplistic approach token for vban_receptor regarding synchronization with audio interfaces.

**Comment by Pomax** [comment] 2019-04-10 14:50
I don't get any audio at all from vban_receptor (but other audio sources work fine, like youtube in a browser, or VLC). I only get those console messages.

**Comment by quiniouben** [comment] 2019-04-10 17:43
Hi, ok.
Let's try to learn more about your system:

- Could you give the output of  `aplay -L` ?
- Is pulseaudio running on your system ?
- If yes, could you give the output of `pulseaudio --dump-conf` ?

**Comment by Pomax** [comment] 2019-04-10 18:15
`aplay -L` gives the following output:
```
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: vc4hdmi [vc4-hdmi], device 0: MAI PCM vc4-hdmi-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Raspian only has ALSA available by default, so there is no pulseaudio available.

The audio from other sources gets sent through the HDMI device though, so would this be a matter of it having picked the wrong device to try to send to?

**Comment by Pomax** [comment] 2019-04-11 15:15
Is there a way to change the device to explicitly use that "device 1" to see if it's just a matter of ALSA sending the audio to the wrong connector? I don't quite know what part of the strings shown should be used for that =/

**Comment by Pomax** [comment] 2019-04-11 17:53
alsamixer information:

![photo_2019-04-11 10 52 39](https://user-images.githubusercontent.com/177243/55979871-069f1380-5c48-11e9-87cf-91b1aaadcef1.jpeg)

**Comment by Pomax** [comment] 2019-04-11 19:12
In a bit of desperation I hooked up a USB sound card, and this command will happily play audio through my speakers now:
```
$ aplay /usr/share/sounds/alsa/Front_Center.wav -D plughw:0,0
```
but vban receptor does not play any audio:
```
$ vban_receptor -i 192.168.1.17 -pp 6980 -s DAW -d plughw=0,0
```

VBAN on the sending computer says that is the correct IP, port, and stream name, with the stream sending to 192.168.1.11, which is the raspberry pi IP according to ifconfig. Pinging from one machine to the other also works fine.

**Comment by quiniouben** [comment] 2019-04-23 07:57
Hi @Pomax , I am sorry for the long delays, free time is lacking a lot this year...
That is weird. The broken pipe clearly says the problem is on alsa side, and if you reach it, it means you correctly receive vban packets from the emitting side.
About selecting the audio device you play on, you should pass vban_receptor the -d option you correctly identified, with labels that `aplay -L` shows (please note the capital "-L", not the small "-l").
Using `aplay -L` you will have knowledge what is the default device.
One reason could be that the emitter sends data at some sample frequency or sample format that the receptor doesn't like too much, eventhough it pretends to do it.
Could you please copy paste the output of the vban_receptor invocation with `-l3` option ?

**Comment by Pomax** [comment] 2019-04-23 16:19
I removed the alsa config overrides for using a USB audio device again, and miraculously, vban_receptor now just works (even without a device flag)...

So I have no idea _why_ it suddenly works, but audio gets sent over the network just fine now (although at 48KHz it's pretty choppy, so I adjusted that down to 22.5KHz at the sender and things sound perfectly fine now)

**Comment by quiniouben** [comment] 2019-04-24 09:16
Hi, I am glad it works now, even though it is a bit frustrating not to know why.
Anyway, I will close this issue.

**Closed by quiniouben** 2019-04-24 09:16 UTC
